FROM node:20-alpine
WORKDIR /app

# On copie tout pour être sûr de ne rien rater
COPY . .

# On se place dans le dossier du backend pour l'installation
WORKDIR /app/mini-services/quiz-service
RUN npm install

EXPOSE 3004

# Script de démarrage robuste
CMD npx prisma@6 generate --schema=../../prisma/schema.prisma && \
    npx prisma@6 db push --skip-generate --schema=../../prisma/schema.prisma && \
    npm run dev
