FROM node:20-alpine
WORKDIR /app

# On garde la structure pour que les imports relatifs ../../src fonctionnent
COPY package*.json ./
COPY mini-services/quiz-service/package*.json ./mini-services/quiz-service/
RUN npm install
RUN cd mini-services/quiz-service && npm install

COPY . .

EXPOSE 3004
WORKDIR /app/mini-services/quiz-service
CMD npx prisma@6 generate --schema=../../prisma/schema.prisma && npx prisma@6 db push --skip-generate --schema=../../prisma/schema.prisma && npm run dev
