// Part 3: Sport MCQ + Cash questions data
export const spMCQ = [
  ["Dans quel pays les Jeux Olympiques modernes ont-ils été créés ?",["France","Grèce","Italie","Angleterre"],0],
  ["Combien de joueurs composent une équipe de football ?",["9","10","11","12"],2],
  ["Quel pays a remporté le plus de Coupes du Monde de football ?",["Allemagne","Brésil","Italie","Argentine"],1],
  ["Quel est le plus grand tournoi de tennis au monde ?",["Roland-Garros","Wimbledon","US Open","Open d'Australie"],1],
  ["Combien de tours compte le Tour de France ?",["18","19","20","21"],3],
  ["Quel sport pratique-t-on au Stade de France pour la finale de Coupe du Monde 1998 ?",["Football","Rugby","Athlétisme","Tennis"],0],
  ["Qui a remporté le plus de titres de champion du monde de Formule 1 ?",["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Alain Prost"],1],
  ["Quelle est la distance d'un marathon ?",["40 km","42,195 km","45 km","50 km"],1],
  ["Quel pays a remporté le plus de médailles aux JO d'été ?",["États-Unis","Chine","Russie","Grande-Bretagne"],0],
  ["Combien de sets faut-il gagner pour remporter un match de tennis masculin en Grand Chelem ?",["2","3","4","5"],1],
  ["Quel club français a remporté la Ligue des Champions en 2020 ?",["PSG","OM","OL","Lyon"],0],
  ["Quelle est la nationalité du coureur cycliste Eddy Merckx ?",["Belge","Français","Néerlandais","Italien"],0],
  ["Combien de périodes dure un match de hockey sur glace ?",["2","3","4","5"],1],
  ["Quel sport Michael Jordan a-t-il pratiqué professionnellement ?",["Baseball","Football","Basket-ball","Golf"],2],
  ["Quelle équipe a remporté la NBA en 2023 ?",["Lakers","Warriors","Nuggets","Celtics"],2],
  ["Combien de points vaut un essai au rugby ?",["3","5","7","10"],1],
  ["Quel pays a remporté la Coupe du Monde de rugby 2023 ?",["Nouvelle-Zélande","Afrique du Sud","France","Angleterre"],1],
  ["Quelle est la nationalité de Rafael Nadal ?",["Espagnole","Portugaise","Brésilienne","Italienne"],0],
  ["Combien de joueurs composent une équipe de basket-ball ?",["4","5","6","7"],1],
  ["Quel athlète détient le record du monde du 100 mètres ?",["Usain Bolt","Carl Lewis","Tyson Gay","Justin Gatlin"],0],
  ["Quelle est la plus grande compétition de football en Europe ?",["Ligue des Champions","Ligue Europa","Coupe du Monde","Euro"],0],
  ["Quel pays a remporté l'Euro 2024 de football ?",["Angleterre","France","Espagne","Allemagne"],2],
  ["Combien de fois la France a-t-elle remporté le Tour de France ?",["30","35","36","40"],2],
  ["Quel sportif est surnommé « le Roi » au basket-ball ?",["Kobe Bryant","LeBron James","Michael Jordan","Shaquille O'Neal"],2],
  ["Quelle est la distance entre les 3 points au basket-ball (NBA) ?",["6,75 m","7,24 m","7,50 m","8,00 m"],1],
  ["Combien de rounds dure un combat de boxe professionnelle ?",["8","10","12","15"],2],
  ["Quel pays a remporté la Coupe du Monde de football 2022 ?",["France","Argentine","Brésil","Croatie"],1],
  ["Quelle est la nationalité de Serena Williams ?",["Américaine","Britannique","Australienne","Canadienne"],0],
  ["Combien de joueurs composent une équipe de rugby à XIII ?",["11","13","15","17"],1],
  ["Quel est le stade le plus grand du monde ?",["Camp Nou","Maracana","Wembley","Signal Iduna Park"],0],
  ["Qui a remporté le Ballon d'Or en 2023 ?",["Lionel Messi","Erling Haaland","Kylian Mbappé","Kevin De Bruyne"],0],
  ["Quel pays est le plus titré aux Jeux Olympiques d'hiver ?",["États-Unis","Norvège","Allemagne","Canada"],1],
  ["Combien de points vaut un panier à 3 points au basket-ball ?",["1","2","3","4"],2],
  ["Quel joueur français a remporté la Ligue des Champions avec le Real Madrid en 2022 ?",["Kylian Mbappé","Antoine Griezmann","Karim Benzema","Olivier Giroud"],2],
  ["Quelle est la vitesse moyenne d'un service de tennis professionnel ?",["150 km/h","180 km/h","200 km/h","220 km/h"],2],
  ["Combien de trous comporte un parcours de golf standard ?",["9","12","18","27"],2],
  ["Quel pays a remporté le plus de titres de champion du monde de handball ?",["France","Allemagne","Suède","Danemark"],2],
  ["Quelle est la nationalité de Tiger Woods ?",["Américaine","Britannique","Sud-africaine","Australienne"],0],
  ["Combien de médailles Michael Phelps a-t-il remportées aux JO ?",["15","20","23","28"],2],
  ["Quel club est surnommé « les Rouge et Blanc » en France ?",["PSG","OM","OL","AS Monaco"],1],
  ["Quelle est la durée d'un match de football ?",["2 x 30 min","2 x 40 min","2 x 45 min","2 x 50 min"],2],
  ["Qui a remporté Roland-Garros le plus de fois chez les hommes ?",["Björn Borg","Rafael Nadal","Novak Djokovic","Roger Federer"],1],
  ["Combien de joueurs composent une équipe de volley-ball ?",["4","5","6","7"],2],
  ["Quel pays a remporté la Coupe du Monde féminine de football en 2023 ?",["États-Unis","Espagne","Angleterre","Allemagne"],1],
  ["Quelle est la nationalité de Max Verstappen ?",["Néerlandaise","Belge","Allemande","Finlandaise"],0],
  ["Combien de Grand Prix compte la saison de Formule 1 (2024) ?",["18","20","22","24"],3],
  ["Quel est le record du monde du saut en longueur ?",["8,50 m","8,70 m","8,95 m","9,00 m"],2],
  ["Quelle équipe NBA est basée à Los Angeles ?",["Lakers","Warriors","Celtics","Bulls"],0],
  ["Combien de sets faut-il gagner pour remporter un match de volley ?",["2","3","4","5"],1],
  ["Qui est le meilleur buteur de l'histoire de la Ligue 1 ?",["Kylian Mbappé","Delio Onnis","Bernard Lacombe","Hervé Revelli"],0],
  ["Quel pays a remporté la Coupe du Monde de cricket 2023 ?",["Inde","Australie","Angleterre","Pakistan"],1],
  ["Quelle est la distance d'un trajet en natation olympique (nage libre) ?",["50 m","100 m","200 m","400 m"],2],
  ["Combien de joueurs composent une équipe de handball ?",["5","6","7","8"],2],
  ["Quel pilote a remporté le plus de Grand Prix en Formule 1 ?",["Michael Schumacher","Lewis Hamilton","Sebastian Vettel","Max Verstappen"],1],
  ["Quelle est la nationalité de Cristiano Ronaldo ?",["Brésilienne","Portugaise","Argentine","Espagnole"],1],
  ["Combien de pays participent à la Coupe du Monde de football ?",["24","28","32","48"],2],
  ["Quel club a remporté le plus de titres de champion de France ?",["PSG","OM","Saint-Étienne","Marseille"],2],
  ["Quelle est la nationalité de Roger Federer ?",["Suisse","Allemand","Autrichien","Britannique"],0],
  ["Combien de points vaut une transformation au rugby ?",["1","2","3","5"],1],
  ["Quel pays a remporté le championnat d'Europe de football 2016 ?",["France","Portugal","Allemagne","Italie"],1],
  ["Quelle est la discipline reine des Jeux Olympiques ?",["100 m","Marathon","Natation","Gymnastique"],1],
  ["Combien de matchs dans une saison de Ligue 1 ?",["34","36","38","40"],2],
  ["Quel est le sport national du Canada ?",["Hockey sur glace","Baseball","Lacrosse","Curling"],0],
  ["Qui a marqué le but en finale de la Coupe du Monde 2018 ?",["Kylian Mbappé","Paul Pogba","Antoine Griezmann","Olivier Giroud"],0],
  ["Quelle est la vitesse moyenne d'une balle de tennis lors d'un service ?",["120 km/h","150 km/h","180 km/h","200 km/h"],2],
  ["Combien de fois la France a-t-elle été championne du monde de football ?",["1","2","3","4"],1],
  ["Quel sport Teddy Riner pratique-t-il ?",["Judo","Karaté","Taekwondo","Boxe"],0],
  ["Quelle est la nationalité de Novak Djokovic ?",["Serbe","Croate","Bosnien","Monténégrin"],0],
  ["Combien de points vaut un coup de pied au rugby ?",["1","2","3","5"],2],
  ["Quel club anglais a remporté la Ligue des Champions en 2019 ?",["Manchester City","Liverpool","Chelsea","Manchester United"],1],
  ["Quelle est la hauteur de la barre pour le saut en hauteur féminin (record du monde) ?",["1,95 m","2,00 m","2,09 m","2,15 m"],2],
  ["Combien de temps dure un match de rugby ?",["60 min","70 min","80 min","90 min"],2],
  ["Quel pays a remporté la Coupe Davis le plus de fois ?",["États-Unis","Australie","France","Grande-Bretagne"],0],
  ["Quelle est la nationalité de Zinedine Zidane ?",["Algérienne","Marocaine","Française","Tunisienne"],2],
  ["Combien de joueurs composent une équipe de water-polo ?",["5","6","7","8"],2],
  ["Qui détient le record du monde du 200 mètres ?",["Usain Bolt","Michael Johnson","Yohan Blake","Noah Lyles"],0],
  ["Quel est le trophée remis au vainqueur de la Ligue des Champions ?",["Coupe UEFA","Trophée UEFA","Coupe aux grandes oreilles","Ballon d'or"],2],
  ["Combien de titres de champion du monde de surf possède le Français ?",["1","2","3","4"],0],
  ["Quelle est la nationalité de LeBron James ?",["Américaine","Canadienne","Britannique","Australienne"],0],
  ["Combien de tours compte le Grand Prix de Monaco de F1 ?",["60","68","70","78"],3],
  ["Quel pays a remporté le plus de Coupe du Monde de football féminin ?",["États-Unis","Allemagne","Japon","Norvège"],0],
  ["Quelle est la distance du lancer du javelot féminin (record du monde) ?",["60 m","65 m","72 m","75 m"],2],
  ["Combien de buts Pelé a-t-il marqués en carrière ?",["800","1000","1200","1283"],1],
  ["Quel est le nom du stade de l'équipe de France de football ?",["Stade de France","Parc des Princes","Stade Roland-Garros","Matmut Atlantique"],0],
  ["Quelle est la nationalité de Martin Fourcade ?",["Suisse","Française","Norvégienne","Italienne"],1],
  ["Combien de joueurs sont sur le terrain en volley-ball ?",["4","6","8","10"],1],
  ["Quel pays a remporté le plus de titres olympiques en escrime ?",["France","Italie","Hongrie","Russie"],1],
  ["Quelle est la nationalité de Stephen Curry ?",["Américaine","Canadienne","Australienne","Britannique"],0],
  ["Combien de matchs gagne-t-on pour remporter une série de playoffs NBA (premier tour) ?",["3","4","5","7"],1],
  ["Quel pays a gagné le plus de Coupe du Monde de handball féminin ?",["Norvège","France","Russie","Danemark"],0],
  ["Quelle est la longueur d'un terrain de football ?",["90 m","100 m","105 m","110 m"],2],
  ["Combien de joueurs composent une équipe de baseball ?",["7","8","9","10"],2],
  ["Qui a remporté le plus de titres de Roland-Garros chez les femmes ?",["Chris Evert","Steffi Graf","Margaret Court","Serena Williams"],1],
  ["Quelle est la nationalité de Lucas Hernandez ?",["Espagnole","Française","Allemande","Portugaise"],1],
  ["Combien de points vaut un panier normal au basket-ball ?",["1","2","3","4"],1],
  ["Quel est le nom de la compétition de golf la plus prestigieuse ?",["The Masters","US Open","Open Britannique","PGA Championship"],0],
  ["Combien de finales de Ligue des Champions le Real Madrid a-t-il remportées ?",["10","13","15","17"],2],
  ["Quelle est la nationalité de Virat Kohli ?",["Indienne","Pakistanais","Sri-Lankais","Bangladais"],0],
  ["Combien de temps dure une période de hockey sur glace ?",["10 min","15 min","20 min","25 min"],2],
  ["Quel pays a remporté la Coupe du Monde de rugby 2019 ?",["Angleterre","Nouvelle-Zélande","Afrique du Sud","Japon"],2],
  ["Quelle est la nationalité de Charles Leclerc ?",["Monégasque","Français","Suisse","Italien"],0],
  ["Combien de points vaut un drop goal au rugby ?",["1","2","3","5"],2],
  ["Quel joueur a remporté le plus de Ballons d'Or ?",["Lionel Messi","Cristiano Ronaldo","Pelé","Johan Cruyff"],0],
  ["Quelle est la longueur d'une piscine olympique ?",["25 m","50 m","75 m","100 m"],1],
  ["Combien de joueurs composent une équipe de cricket ?",["9","10","11","12"],2],
  ["Qui a remporté le Tour de France 2024 ?",["Tadej Pogacar","Jonas Vingegaard","Remco Evenepoel","Primoz Roglic"],0],
  ["Quelle est la nationalité de Giannis Antetokounmpo ?",["Grec","Américain","Nigérian","Espagnol"],0],
  ["Combien de temps dure un match de basket-ball NBA ?",["2 x 20 min","4 x 10 min","4 x 12 min","2 x 25 min"],2],
  ["Quel pays a remporté la Coupe du Monde de ski alpin le plus souvent ?",["Autriche","Suisse","France","Italie"],0],
  ["Quelle est la distance du triple saut masculin (record du monde) ?",["16 m","17 m","18,29 m","19 m"],2],
  ["Combien de joueurs composent une équipe de futsal ?",["4","5","6","7"],1],
  ["Quel club français a eu l'invincibilité en Ligue 1 ?",["PSG","Nantes","Saint-Étienne","Monaco"],1],
  ["Quelle est la nationalité de Marc Márquez ?",["Espagnole","Italienne","Portugaise","Française"],0],
  ["Combien de sets en finale de Roland-Garros hommes ?",["3","4","5","6"],2],
  ["Quel pays a remporté le plus de médailles d'or en natation aux JO ?",["États-Unis","Australie","Chine","Grande-Bretagne"],0],
  ["Quelle est la nationalité d'Erling Haaland ?",["Norvégienne","Suédoise","Danoise","Islandaise"],0],
  ["Combien de courses compte le championnat du monde de MotoGP (2024) ?",["16","18","20","22"],2],
  ["Quel pays a organisé les JO d'hiver 2022 ?",["Japon","Corée du Sud","Chine","Canada"],2],
  ["Quelle est la distance du lancer du poids masculin (record du monde) ?",["20 m","22 m","23,56 m","25 m"],2],
  ["Combien de joueurs sur le terrain en handball ?",["5","6","7","8"],2],
  ["Qui a remporté le plus de Grand Chelem en tennis féminin ?",["Serena Williams","Margaret Court","Steffi Graf","Martina Navratilova"],1],
  ["Quelle est la nationalité de Luka Doncic ?",["Slovène","Croatie","Serbe","Bosnien"],0],
  ["Combien de matchs dans la phase de groupes de la Ligue des Champions ?",["4","5","6","8"],2],
  ["Quel pays a remporté le plus de Coupe du Monde de volley-ball ?",["Brésil","Pologne","Russie","États-Unis"],2],
  ["Quelle est la vitesse maximale d'une Formule 1 ?",["300 km/h","320 km/h","350 km/h","372 km/h"],3],
  ["Combien de joueurs composent une équipe de flag football ?",["5","6","7","11"],2],
  ["Quel pays a remporté la Coupe du Monde 2014 de football ?",["Allemagne","Argentine","Brésil","Pays-Bas"],0],
  ["Quelle est la nationalité de Kylian Mbappé ?",["Française","Camerounaise","Algérienne","Marocaine"],0],
  ["Combien de médailles d'or la France a-t-elle remportées aux JO de Paris 2024 ?",["16","20","24","28"],0],
  ["Quel pays a remporté la Copa America 2024 ?",["Brésil","Argentine","Colombie","Uruguay"],1],
  ["Quelle est la nationalité d'Anthony Joshua ?",["Britannique","Nigérian","Américain","Canadien"],0],
  ["Combien de temps dure un round de boxe professionnelle ?",["2 min","3 min","4 min","5 min"],1],
  ["Quel est le sport le plus populaire en Inde ?",["Cricket","Hockey","Football","Tennis"],0],
  ["Quelle est la nationalité de Daniil Medvedev ?",["Russe","Ukrainien","Biélorusse","Géorgien"],0],
  ["Combien de joueurs composent une équipe de rugby à 7 ?",["5","7","9","11"],1],
  ["Qui a marqué le plus de buts en sélection nationale ?",["Cristiano Ronaldo","Lionel Messi","Pelé","Ferenc Puskás"],0],
  ["Quelle est la nationalité de Carlos Alcaraz ?",["Espagnole","Argentine","Brésilienne","Italienne"],0],
  ["Combien de titres NBA les Lakers ont-ils remportés ?",["14","16","17","20"],2],
  ["Quel pays a remporté le plus de Coupe du Monde de football féminin U20 ?",["États-Unis","Allemagne","Japon","Brésil"],0],
  ["Quelle est la hauteur du filet au volley-ball masculin ?",["2,20 m","2,35 m","2,43 m","2,50 m"],2],
  ["Combien de matchs en saison régulière NFL ?",["14","16","17","18"],1],
  ["Quel pays a remporté le plus de titres olympiques en judo ?",["Japon","France","Corée du Sud","Brésil"],0],
  ["Quelle est la nationalité de Jonas Vingegaard ?",["Danoise","Norvégienne","Suédoise","Néerlandaise"],0],
  ["Combien de points vaut une pénalité au rugby ?",["2","3","5","7"],1],
  ["Quel est le plus vieux club de football français ?",["Le Havre","PSG","Saint-Étienne","OM"],0],
  ["Quelle est la nationalité de Simone Biles ?",["Américaine","Britannique","Canadienne","Australienne"],0],
  ["Combien de joueurs sur le terrain en volley-ball féminin ?",["4","5","6","7"],2],
  ["Qui a remporté le plus de fois le Tour de France ?",["Jacques Anquetil","Bernard Hinault","Lance Armstrong","Eddy Merckx"],0],
  ["Quel pays a remporté la Coupe du Monde de basket-ball 2023 ?",["États-Unis","Serbie","Allemagne","France"],2],
  ["Quelle est la longueur d'un court de tennis ?",["20 m","23,77 m","25 m","28 m"],1],
  ["Combien de joueurs composent une équipe de korfball ?",["6","7","8","10"],2],
  ["Quel pays est à l'origine du judo ?",["Chine","Corée","Japon","Thaïlande"],2],
  ["Quelle est la nationalité de Declan Rice ?",["Britannique","Irlandaise","Écossaise","Galloise"],0],
  ["Combien de tours compte le Grand Prix de Belgique ?",["40","42","44","46"],2],
];

export const spCash = [
  ["Quel pays a remporté la Coupe du Monde de football 1998 ?",["france"]],
  ["Combien de joueurs composent une équipe de football ?",["11","onze"]],
  ["Quel est le stade où se joue la finale de la Ligue des Champions 2022 ?",["stade de france"]],
  ["Comment s'appelle le joueur surnommé CR7 ?",["cristiano ronaldo","ronaldo"]],
  ["Quel pays a remporté le plus de titres olympiques en football ?",["hongrie","brazil","bresil","argentine"]],
  ["Combien de minutes dure un match de football ?",["90","quatre-vingt-dix"]],
  ["Quel est le nom du trophée de la Coupe du Monde de football ?",["coupe du monde","trophee","coupe jules rimet"]],
  ["Comment s'appelle le goélicien célèbre des années 2000 en Formule 1 ?",["michael schumacher","schumacher"]],
  ["Quel club français a remporté la Ligue des Champions en 1993 ?",["om","olympique de marseille","marseille"]],
  ["Combien de Ballons d'Or Lionel Messi a-t-il remportés ?",["8","huit"]],
  ["Quel pays a gagné le plus de fois le Tour de France ?",["france"]],
  ["Comment s'appelle le tennisman surnommé le Borg des Canaries ?",["rafael nadal","nadal"]],
  ["Combien de points vaut un essai au rugby ?",["5","cinq"]],
  ["Quel pays a remporté le plus de Coupes du Monde de rugby ?",["nouvelle-zelande","afrique du sud","afrique du sud"]],
  ["Comment s'appelle la compétition de ski alpin la plus célèbre ?",["coupe du monde de ski","world cup","coupe du monde"]],
  ["Quel est le nom de l'équipe de basket de Los Angeles ?",["lakers","los angeles lakers"]],
  ["Combien de joueurs composent une équipe de rugby à XV ?",["15","quinze"]],
  ["Quel pays a remporté l'Euro de football 2020 ?",["italie"]],
  ["Comment s'appelle le sprinter jamaïcain le plus rapide du monde ?",["usain bolt","bolt"]],
  ["Quel est le nom du champion du monde de Formule 1 en 2021 et 2022 ?",["max verstappen","verstappen"]],
  ["Combien de tours compte le Tour de France ?",["21","vingt et un"]],
  ["Quel pays a remporté le plus de médailles aux JO 2024 ?",["etats-unis","usa","etats unis"]],
  ["Comment s'appelle la compétition de golf entre l'Europe et les États-Unis ?",["ryder cup"]],
  ["Quel est le record du monde du 100 mètres en secondes ?",["9.58","9,58","neuf cinquante-huit"]],
  ["Combien de fois le Brésil a-t-il remporté la Coupe du Monde ?",["5","cinq"]],
  ["Quel est le nom du stade de Manchester United ?",["old trafford"]],
  ["Combien de sets pour gagner un match de tennis féminin en Grand Chelem ?",["2","deux"]],
  ["Quel pays a remporté la Coupe du Monde de handball 2017 ?",["france"]],
  ["Comment s'appelle le plus grand cycliste belge de tous les temps ?",["eddy merckx","merckx"]],
  ["Combien de points vaut une pénalité au rugby ?",["3","trois"]],
  ["Quel est le nom de l'équipe de basket de Boston ?",["celtics","boston celtics"]],
  ["Combien de médailles d'or Michael Phelps a-t-il remportées ?",["23","vingt-trois"]],
  ["Quel pays a remporté la Coupe du Monde féminine de football 2019 ?",["etats-unis","usa"]],
  ["Comment s'appelle le pilote allemand champion du monde de F1 ?",["michael schumacher","sebastian vettel","vettel"]],
  ["Combien de joueurs sur le terrain en handball ?",["7","sept"]],
  ["Quel pays a remporté le plus de titres en Coupe Davis ?",["etats-unis","usa","australie"]],
  ["Comment s'appelle le champion du monde 2022 de natation française ?",["léon marchand","marchand"]],
  ["Combien de matchs en saison régulière de la NBA ?",["82","quatre-vingt-deux"]],
  ["Quel est le nom du club de football de Madrid ?",["real madrid","madrid"]],
  ["Combien de finales de Coupe du Monde le Brésil a-t-il disputées ?",["7","sept"]],
  ["Comment s'appelle le judoka français le plus titré ?",["teddy riner","riner"]],
  ["Combien de médailles la France a-t-elle obtenues aux JO 2012 ?",["35","34","15"]],
  ["Quel pays a remporté la Copa America 2021 ?",["argentine"]],
  ["Comment s'appelle la compétition européenne de rugby ?",["six nations","tournoi des six nations"]],
  ["Combien de temps dure une période de hockey sur glace ?",["20","vingt","vingt minutes"]],
  ["Quel est le nom du club de football de Liverpool ?",["liverpool fc","liverpool"]],
  ["Combien de joueurs composent une équipe de volley-ball ?",["6","six"]],
  ["Quel pays a remporté le plus de Coupe du Monde de ski ?",["autriche","suisse"]],
  ["Comment s'appelle le tennisman suisse avec 20 titres du Grand Chelem ?",["roger federer","federer"]],
  ["Combien de buts a marqués Kylian Mbappé en Coupe du Monde 2022 ?",["8","huit"]],
  ["Quel est le nom du champion olympique du marathon 2024 ?",["tamirat tola","tola","bashir abdi","abdi"]],
  ["Combien de points vaut un drop au rugby ?",["3","trois"]],
  ["Quel pays a remporté le championnat d'Europe de basket-ball 2022 ?",["espagne"]],
  ["Comment s'appelle la fédération internationale de football ?",["fifa"]],
  ["Combien de times le Real Madrid a-t-il gagné la Ligue des Champions ?",["15","quinze"]],
];
