// Part 4: Musique MCQ + Cash questions data
export const muMCQ = [
  ["Quel est l'instrument de musique le plus joué au monde ?",["Guitare","Piano","Violon","Batterie"],0],
  ["Combien de touches a un piano standard ?",["76","82","88","92"],2],
  ["Quel compositeur est devenu sourd ?",["Mozart","Beethoven","Bach","Chopin"],1],
  ["Quelle est la chanson la plus vendue de tous les temps ?",["White Christmas","Bohemian Rhapsody","Thriller","Candle in the Wind"],2],
  ["Quel artiste a vendu le plus d'albums dans le monde ?",["Elvis Presley","The Beatles","Michael Jackson","Madonna"],1],
  ["Combien de cordes a une guitare classique ?",["4","5","6","8"],2],
  ["Quel genre musical est originaire de la Jamaïque ?",["Reggae","Salsa","Samba","Tango"],0],
  ["Qui chante « Shape of You » ?",["Ed Sheeran","Justin Bieber","Sam Smith","Bruno Mars"],0],
  ["Quel est le plus grand festival de musique en France ?",["Hellfest","Rock en Seine","Solidays","Les Vieilles Charrues"],3],
  ["Combien de musiciens composent un quatuor à cordes ?",["2","3","4","5"],2],
  ["Quel artiste est surnommé le Roi de la Pop ?",["Elvis Presley","Michael Jackson","Prince","Freddie Mercury"],1],
  ["Quelle est la capitale de la musique country ?",["Nashville","Memphis","Austin","New Orleans"],0],
  ["Combien de symphonies Beethoven a-t-il composées ?",["5","7","9","12"],2],
  ["Qui est la chanteuse du titre « Bad Romance » ?",["Lady Gaga","Beyoncé","Rihanna","Katy Perry"],0],
  ["Quel instrument de musique a le plus de cordes d'un orchestre ?",["Violon","Alto","Violoncelle","Contrebasse"],3],
  ["Quelle est la période musicale de Mozart ?",["Baroque","Classique","Romantique","Moderne"],1],
  ["Qui chante « Rolling in the Deep » ?",["Adele","Sia","Alicia Keys","Amy Winehouse"],0],
  ["Combien de notes y a-t-il dans une gamme ?",["5","7","8","12"],1],
  ["Quel groupe a composé « Stairway to Heaven » ?",["Led Zeppelin","Pink Floyd","The Who","Deep Purple"],0],
  ["Quelle est la vitesse d'une valse ?",["60 bpm","80 bpm","100 bpm","120 bpm"],2],
  ["Qui a composé les Quatre Saisons ?",["Bach","Vivaldi","Mozart","Haydn"],1],
  ["Quel artiste français chante « La Vie en rose » ?",["Édith Piaf","Charles Aznavour","Jacques Brel","Maurice Chevalier"],0],
  ["Combien de musiciens composent un quintette ?",["3","4","5","6"],2],
  ["Qui est le leader du groupe U2 ?",["Bono","The Edge","Adam Clayton","Larry Mullen Jr."],0],
  ["Quel genre musical est associé à New Orleans ?",["Jazz","Blues","Country","Rock"],0],
  ["Combien de temps dure la 5e symphonie de Beethoven (environ) ?",["20 min","25 min","33 min","45 min"],2],
  ["Qui chante « Imagine » ?",["John Lennon","Paul McCartney","George Harrison","Ringo Starr"],0],
  ["Quel est le nom du premier album de Daft Punk ?",["Homework","Discovery","Alive 2007","Random Access Memories"],0],
  ["Combien de notes dans une octave ?",["6","7","8","12"],2],
  ["Quel groupe a composé « Bohemian Rhapsody » ?",["The Beatles","Queen","Pink Floyd","Led Zeppelin"],1],
  ["Quelle est la nationalité de Chopin ?",["Française","Polonaise","Allemande","Tchèque"],1],
  ["Qui chante « Despacito » ?",["Daddy Yankee","Luis Fonsi","J Balvin","Shakira"],1],
  ["Combien de cordes a un violon ?",["3","4","5","6"],1],
  ["Quel artiste a popularisé le moonwalk ?",["James Brown","Michael Jackson","Prince","Usher"],1],
  ["Quelle est la mesure d'un morceau de jazz ?",["2/4","3/4","4/4","6/8"],2],
  ["Qui est la chanteuse de « Halo » ?",["Beyoncé","Rihanna","Alicia Keys","Mary J. Blige"],0],
  ["Combien de membres composait les Beatles ?",["3","4","5","6"],1],
  ["Quel compositeur a écrit la Clé de Sol ?",["Bach","Mozart","Beethoven","Debussy"],0],
  ["Qui a chanté « Comme d'habitude » (reprise en My Way) ?",["Claude François","Charles Aznavour","Serge Gainsbourg","Jacques Brel"],0],
  ["Combien de genres de voix existe-t-il dans la musique classique ?",["2","3","4","6"],2],
  ["Quel est le groupe de rock le plus vendu de tous les temps ?",["Led Zeppelin","AC/DC","The Beatles","Pink Floyd"],2],
  ["Quelle est la nationalité de Bach ?",["Française","Allemand","Autrichienne","Italien"],1],
  ["Qui chante « Blinding Lights » ?",["The Weeknd","Daft Punk","Bruno Mars","Ed Sheeran"],0],
  ["Combien de lignes a une portée musicale ?",["3","4","5","6"],2],
  ["Quel groupe français a chanté « Une Nuit à Paris » ?",["Daft Punk","Air","Justice","Cassius"],0],
  ["Quelle est la période du jazz classique ?",["1920-1940","1940-1960","1960-1980","1980-2000"],0],
  ["Qui a composé le Boléro ?",["Ravel","Debussy","Saint-Saëns","Fauré"],0],
  ["Combien de membres composait le groupe AC/DC ?",["3","4","5","6"],1],
  ["Quelle est la chanson la plus diffusée sur Spotify (2024) ?",["Blinding Lights","Shape of You","Dance Monkey","Someone You Loved"],0],
  ["Qui est le chanteur de Coldplay ?",["Chris Martin","Thom Yorke","Matt Bellamy","Brandon Flowers"],0],
  ["Combien de demi-tons dans une octave ?",["7","10","12","14"],2],
  ["Quel compositeur a écrit « Le Lac des Cygnes » ?",["Tchaïkovski","Stravinsky","Prokofiev","Rachmaninov"],0],
  ["Qui chante « Dernière danse » ?",["Indila","Stromae","Maître Gims","Louane"],0],
  ["Combien de cordes a une harpe ?",["20","30","47","60"],2],
  ["Quel est le plus ancien instrument de musique ?",["Flûte","Tambour","Luth","Harpe"],0],
  ["Qui a composé la musique du film Le Parrain ?",["John Williams","Nino Rota","Hans Zimmer","Ennio Morricone"],1],
  ["Combien de types de clefs musicales existe-t-il ?",["2","3","4","5"],1],
  ["Quelle est la nationalité de Debussy ?",["Française","Allemande","Belge","Suisse"],0],
  ["Qui chante « Avenir » (A Million Dreams) ?",["Louane","Indila","Zaz","Angèle"],0],
  ["Combien de notes dans un arpège de septième ?",["3","4","5","6"],1],
  ["Quel est le genre musical de Stromae ?",["Pop","Électro","Rap","Chanson française"],0],
  ["Quelle est la forme musicale la plus utilisée dans la musique classique ?",["Sonate","Symphonie","Concerto","Opéra"],0],
  ["Combien de pièces un clavecin possède-t-il (environ) ?",["1","2","3","4"],1],
  ["Qui a composé le « Canon de Pachelbel » ?",["Johann Pachelbel","Bach","Vivaldi","Handel"],0],
  ["Combien de joueurs composent un orchestre symphonique ?",["40","60","80","100"],2],
  ["Quel artiste est surnommé Queen of Pop ?",["Madonna","Beyoncé","Cher","Whitney Houston"],0],
  ["Quelle est la nationalité de Schubert ?",["Allemand","Autrichien","Tchèque","Suisse"],1],
  ["Qui chante « Naviguer » ?",["Stromae","Jul","Pomme","Angèle"],0],
  ["Combien de temps dure la sonate au Clair de Lune de Beethoven ?",["10 min","15 min","20 min","25 min"],1],
  ["Quel est le plus grand festival de musique au monde ?",["Tomorrowland","Coachella","Glastonbury","Summerfest"],3],
  ["Qui a composé la musique de Star Wars ?",["Hans Zimmer","John Williams","Danny Elfman","Howard Shore"],1],
  ["Combien de chœurs dans une messe musicale ?",["3","4","5","6"],2],
  ["Quelle est la nationalité de Verdi ?",["Française","Italienne","Allemande","Espagnole"],1],
  ["Qui chante « Papillon » ?",["Nikal","Stromae","Gims","Louane"],3],
  ["Combien de notes dans un accord majeur ?",["2","3","4","5"],1],
  ["Quel genre musical est né à Détroit ?",["Techno","House","Jazz","Blues"],0],
  ["Quelle est la période musicale de Debussy ?",["Classique","Romantique","Impressionniste","Moderne"],2],
  ["Combien de flûtes dans un orchestre symphonique ?",["1","2","3","4"],1],
  ["Quel artiste a composé « Thriller » ?",["Prince","Michael Jackson","Stevie Wonder","James Brown"],1],
  ["Qui est le chanteur de Muse ?",["Matt Bellamy","Chris Martin","Thom Yorke","Bono"],0],
  ["Combien de mesures dans un blues de 12 mesures ?",["8","10","12","16"],2],
  ["Quelle est la nationalité de Vivaldi ?",["Française","Italienne","Allemande","Espagnole"],1],
  ["Qui chante « Taki Taki » ?",["DJ Snake","Daddy Yankee","J Balvin","Maluma"],0],
  ["Combien de cordes a un violoncelle ?",["3","4","5","6"],1],
  ["Quel est le genre musical le plus écouté en France (2024) ?",["Pop","Rap","Rock","Électro"],1],
  ["Qui a composé « La Mer » ?",["Debussy","Ravel","Fauré","Saint-Saëns"],0],
  ["Combien de chanteurs dans un chœur mixte ?",["2","3","4","6"],2],
  ["Quelle est la nationalité de Mozart ?",["Allemand","Autrichien","Italien","Tchèque"],1],
  ["Qui chante « Don't Start Now » ?",["Dua Lipa","Ariana Grande","Billie Eilish","Taylor Swift"],0],
  ["Combien de cordes a une basse ?",["3","4","5","6"],1],
  ["Quel est le plus grand marché de la musique ?",["États-Unis","Japon","Allemagne","Royaume-Uni"],0],
  ["Qui a composé la musique de Harry Potter ?",["John Williams","Hans Zimmer","Howard Shore","Danny Elfman"],0],
  ["Combien de types de trompettes existe-t-il ?",["2","3","4","5"],1],
  ["Quelle est la nationalité de Tchaïkovski ?",["Français","Russe","Polonais","Tchèque"],1],
  ["Qui chante « Todo de ti » ?",["Rosalía","Shakira","Karol G","Becky G"],0],
  ["Combien de temps dure un concerto classique en moyenne ?",["15 min","20 min","30 min","45 min"],2],
  ["Quel genre musical est originaire de la Nouvelle-Orléans ?",["Blues","Jazz","Zydeco","Swing"],1],
  ["Qui est la chanteuse du titre « Hips Don't Lie » ?",["Shakira","Beyoncé","Rihanna","Jennifer Lopez"],0],
  ["Combien de partitions Bach a-t-il composées (approximativement) ?",["500","800","1000","1500"],2],
  ["Quel groupe a chanté « Hotel California » ?",["Eagles","Fleetwood Mac","The Doors","Creedence Clearwater Revival"],0],
  ["Quelle est la nationalité de Grieg ?",["Suédois","Norvégien","Danois","Finlandais"],1],
  ["Qui chante « Je veux » ?",["Zaz","Indila","Louane","Angèle"],0],
  ["Combien de cordes a un banjo ?",["4","5","6","8"],1],
  ["Quel compositeur a écrit l'Oratorio de Noël ?",["Bach","Handel","Vivaldi","Haydn"],1],
  ["Combien de membres composait le groupe Pink Floyd ?",["3","4","5","6"],1],
  ["Quelle est la nationalité de Schumann ?",["Allemand","Autrichien","Tchèque","Suisse"],0],
  ["Qui chante « Watermelon Sugar » ?",["Harry Styles","Ed Sheeran","Shawn Mendes","John Mayer"],0],
  ["Combien de tonalités majeures existe-t-il ?",["8","10","12","15"],2],
  ["Quel genre musical est né à Chicago ?",["House","Techno","Jazz","Blues"],0],
  ["Quelle est la nationalité de Rachmaninov ?",["Polonais","Russe","Tchèque","Allemand"],1],
  ["Qui chante « Alors on danse » ?",["Stromae","Maître Gims","Jul","Booba"],0],
  ["Combien de timbales dans un orchestre symphonique ?",["2","3","4","5"],2],
  ["Quel artiste est surnommé the Voice ?",["Whitney Houston","Celine Dion","Mariah Carey","Adele"],0],
  ["Combien de tempo y a-t-il dans un adagio ?",["40-60 bpm","60-80 bpm","80-100 bpm","100-120 bpm"],0],
  ["Quelle est la nationalité de Paganini ?",["Français","Italien","Allemand","Espagnol"],1],
  ["Qui chante « Shade » ?",["Stromae","Booba","Orelsan","Nekfeu"],0],
  ["Combien de tubes avait Elvis Presley au Billboard ?",["80","100","120","150"],2],
  ["Quel est le groupe le plus vendu en France ?",["Indochine","Daft Punk","Telephone","Noir Désir"],0],
  ["Quelle est la nationalité de Liszt ?",["Allemand","Autrichien","Hongrois","Tchèque"],2],
  ["Qui chante « Levitating » ?",["Dua Lipa","Lady Gaga","Doja Cat","Ariana Grande"],0],
  ["Combien de cordes a un ukulélé ?",["3","4","5","6"],1],
  ["Quelle est la période musicale de Bach ?",["Renaissance","Baroque","Classique","Romantique"],1],
  ["Combien de personnes assistent au festival de Glastonbury ?",["100 000","150 000","200 000","300 000"],2],
  ["Qui a composé la musique de Inception ?",["Hans Zimmer","John Williams","Thomas Newman","James Horner"],0],
  ["Combien de percussions dans un orchestre symphonique ?",["4","6","8","10"],2],
  ["Quelle est la nationalité de Mahler ?",["Allemand","Autrichien","Tchèque","Suisse"],1],
  ["Qui chante « Easy On Me » ?",["Adele","Sia","Billie Eilish","Dua Lipa"],0],
  ["Combien de mouvements dans une symphonie classique ?",["2","3","4","5"],2],
  ["Quel genre musical est né à Kingston ?",["Reggae","Dub","Ska","Dancehall"],2],
  ["Qui est la chanteuse de « Umbrella » ?",["Rihanna","Beyoncé","Nicki Minaj","Cardi B"],0],
  ["Combien de répertoires de Debussy sont-ils catalogués ?",["100","150","200","250"],0],
  ["Quel groupe a chanté « Smells Like Teen Spirit » ?",["Nirvana","Pearl Jam","Soundgarden","Alice in Chains"],0],
  ["Quelle est la nationalité de Dvořák ?",["Tchèque","Slovaque","Polonais","Hongrois"],0],
  ["Qui chante « Chandelier » ?",["Sia","Adele","Alicia Keys","Pink"],0],
  ["Combien de cordes a un oud ?",["5","6","8","10"],1],
  ["Quel compositeur est surnommé le père de la symphonie ?",["Haydn","Mozart","Beethoven","Bach"],0],
  ["Combien d'albums Metallica ont-ils vendus ?",["50 millions","80 millions","100 millions","125 millions"],3],
  ["Quel est le single le plus vendu en France ?",["La Vie en rose","Dernière danse","Ne me quitte pas","Les Champs-Élysées"],2],
  ["Quelle est la nationalité de Prokofiev ?",["Russe","Ukrainien","Géorgien","Polonais"],0],
  ["Qui chante « Flowers » ?",["Miley Cyrus","Dua Lipa","Taylor Swift","Billie Eilish"],0],
  ["Combien de clés existent en solfège ?",["2","3","4","5"],1],
  ["Quel genre musical est né en Alabama ?",["Country","Blues","Jazz","Rock"],0],
  ["Qui a composé le « Requiem » en Ré mineur ?",["Mozart","Verdi","Brahms","Fauré"],0],
  ["Combien de ventes mondiales pour l'album Thriller ?",["40 millions","50 millions","65 millions","70 millions"],2],
  ["Quel groupe a chanté « Comfortably Numb » ?",["Pink Floyd","Led Zeppelin","The Who","Deep Purple"],0],
  ["Quelle est la nationalité de Brahms ?",["Allemand","Autrichien","Tchèque","Suisse"],0],
  ["Qui chante « J'ai vu » ?",["Niagara","Stromae","Gims","Louane"],0],
  ["Combien de temps dure l'album Dark Side of the Moon ?",["35 min","38 min","42 min","50 min"],2],
  ["Quel groupe a composé « Yesterday » ?",["The Beatles","The Rolling Stones","The Kinks","The Who"],0],
  ["Combien de pianos un pianiste utilise-t-il lors d'un concert ?",["1","2","3","4"],0],
];

export const muCash = [
  ["Quel compositeur est devenu sourd ?",["beethoven"]],
  ["Combien de touches a un piano ?",["88","quatre-vingt-huit"]],
  ["Comment s'appelle le Roi de la Pop ?",["michael jackson","jackson"]],
  ["Quel artiste chante la chanson Imagine ?",["john lennon","lennon"]],
  ["Combien de cordes a une guitare ?",["6","six"]],
  ["Quel groupe a composé Bohemian Rhapsody ?",["queen"]],
  ["Comment s'appelle la chanteuse de Bad Romance ?",["lady gaga","gaga"]],
  ["Combien de membres composaient les Beatles ?",["4","quatre"]],
  ["Quel genre musical est originaire de la Jamaïque ?",["reggae"]],
  ["Comment s'appelle le festival de musique à Nantes ?",["hellfest","rock en seine","voyage sonique"]],
  ["Combien de cordes a un violon ?",["4","quatre"]],
  ["Quel artiste français a chanté La Vie en rose ?",["edith piaf","piaf"]],
  ["Qui a composé le Boléro ?",["ravel"]],
  ["Combien de cordes a une basse ?",["4","quatre"]],
  ["Quel genre musical est originaire de la Nouvelle-Orléans ?",["jazz"]],
  ["Comment s'appelle le chanteur de Coldplay ?",["chris martin","martin"]],
  ["Combien de notes y a-t-il dans une gamme ?",["7","sept"]],
  ["Quel groupe a chanté Stairway to Heaven ?",["led zeppelin"]],
  ["Comment s'appelle le chanteur de Muse ?",["matt bellamy","bellamy"]],
  ["Combien de touches a un saxophone ?",["aucune","0","zero"]],
  ["Quel compositeur a écrit les Quatre Saisons ?",["vivaldi"]],
  ["Qui chante Shape of You ?",["ed sheeran","sheeran"]],
  ["Combien de lignes a une portée musicale ?",["5","cinq"]],
  ["Quel artiste est surnommé Queen of Pop ?",["madonna"]],
  ["Comment s'appelle le premier album de Daft Punk ?",["homework"]],
  ["Combien de membres composait le groupe Nirvana ?",["3","trois"]],
  ["Quelle est la capitale de la musique country ?",["nashville"]],
  ["Qui a composé la musique de Star Wars ?",["john williams","williams"]],
  ["Combien de temps dure une octave en demi-tons ?",["12","douze"]],
  ["Quel groupe français a composé One More Time ?",["daft punk"]],
  ["Comment s'appelle le chanteur de U2 ?",["bono"]],
  ["Combien de cordes a une harpe ?",["47","quarante-sept"]],
  ["Quel compositeur a écrit le Lac des Cygnes ?",["tchaikovski"]],
  ["Qui chante Blinding Lights ?",["the weeknd","weeknd","abel tesfaye"]],
  ["Combien de types de clefs existe-t-il ?",["3","trois","4","quatre"]],
  ["Quelle est la nationalité de Chopin ?",["polonais","polonaise"]],
  ["Quel artiste chante Despacito ?",["luis fonsi","fonsi"]],
  ["Combien de symphonies Beethoven a-t-il composées ?",["9","neuf"]],
  ["Comment s'appelle le genre musical de Stromae ?",["pop","electro","electropop"]],
  ["Quel groupe a chanté Comfortably Numb ?",["pink floyd"]],
  ["Combien de notes dans un accord ?",["3","trois"]],
  ["Qui a composé la musique du film Harry Potter ?",["john williams","williams"]],
  ["Quelle est la chanson la plus vendue de tous les temps ?",["thriller","white christmas","candle in the wind"]],
  ["Combien de cordes a un banjo ?",["5","cinq"]],
  ["Quel est le plus grand festival de musique en France ?",["les vieilles charrues","vieilles charrues","hellfest"]],
  ["Comment s'appelle le compositeur du Canon ?",["pachelbel","johann pachelbel"]],
  ["Combien de cordes a un ukulélé ?",["4","quatre"]],
  ["Quel groupe a chanté Hotel California ?",["eagles"]],
  ["Quelle est la nationalité de Debussy ?",["francaise","française"]],
  ["Qui chante Rolling in the Deep ?",["adele"]],
  ["Combien de cordes a un violoncelle ?",["4","quatre"]],
  ["Quel artiste a popularisé le moonwalk ?",["michael jackson","jackson"]],
  ["Comment s'appelle le genre né à Détroit ?",["techno"]],
  ["Combien de temps dure le Boléro de Ravel ?",["15 min","15 minutes","quinze"]],
  ["Quelle chanteuse française interprète Je veux ?",["zaz"]],
  ["Combien de membres composait le groupe Daft Punk ?",["2","deux"]],
  ["Quel est l'album le plus vendu de tous les temps ?",["thriller"]],
];
