// Part 2: Cinéma & Séries MCQ + Cash questions data
export const csMCQ = [
  ["Qui réalise le film Inception (2010) ?",["Steven Spielberg","Christopher Nolan","James Cameron","Ridley Scott"],1],
  ["Quel acteur joue le rôle de Jack dans Titanic ?",["Brad Pitt","Leonardo DiCaprio","Tom Cruise","Johnny Depp"],1],
  ["Quel est le premier long-métrage d'animation Disney ?",["Blanche-Neige","Cendrillon","Fantasia","Pinocchio"],0],
  ["Dans quelle saga trouve-t-on le personnage de Darth Vader ?",["Star Trek","Star Wars","Stargate","Battlestar Galactica"],1],
  ["Qui joue Forrest Gump dans le film éponyme ?",["Tom Hanks","Robert Redford","Dustin Hoffman","Robin Williams"],0],
  ["Quel film a remporté la Palme d'or au Festival de Cannes en 2019 ?",["Joker","Parasite","1917","Once Upon a Time in Hollywood"],1],
  ["Quelle actrice a incarné Wonder Woman au cinéma ?",["Gal Gadot","Margot Robbie","Scarlett Johansson","Angelina Jolie"],0],
  ["Qui a réalisé le film Pulp Fiction ?",["Quentin Tarantino","Martin Scorsese","David Fincher","Coen Brothers"],0],
  ["Quel est le dernier film de la saga Harry Potter ?",["Les Reliques de la Mort - Partie 1","Les Reliques de la Mort - Partie 2","Le Prince de Sang-Mêlé","L'Ordre du Phénix"],1],
  ["Dans quel film trouve-t-on le personnage de Tony Montana ?",["Scarface","Le Parrain","Goodfellas","Casino"],0],
  ["Quelle est la boisson préférée de James Bond ?",["Whisky","Martini","Vodka","Champagne"],1],
  ["Qui incarne Iron Man dans le MCU ?",["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"],2],
  ["Quel est le plus grand succès au box-office mondial (2024) ?",["Avatar","Avengers: Endgame","Titanic","Star Wars: The Force Awakens"],0],
  ["Qui a réalisé le film Interstellar ?",["Steven Spielberg","Christopher Nolan","Denis Villeneuve","Ridley Scott"],1],
  ["Quel film de Miyazaki a remporté l'Oscar du meilleur film d'animation en 2003 ?",["Princesse Mononoké","Le Voyage de Chihiro","Mon voisin Totoro","Le Château ambulant"],1],
  ["Dans quelle série TV trouve-t-on Walter White ?",["Dexter","Breaking Bad","Better Call Saul","The Wire"],1],
  ["Quel acteur incarne le Joker dans The Dark Knight (2008) ?",["Jared Leto","Jack Nicholson","Heath Ledger","Joaquin Phoenix"],2],
  ["Quel film d'animation Pixar est sorti en premier ?",["Toy Story","Ratatouille","Le Monde de Nemo","Monstres et Compagnie"],0],
  ["Quelle actrice joue le rôle principal dans Kill Bill ?",["Angelina Jolie","Uma Thurman","Lucy Liu","Cameron Diaz"],1],
  ["Dans quel film Keanu Reeves découvre-il la matrice ?",["Speed","John Wick","Matrix","Point Break"],2],
  ["Qui a réalisé E.T. l'extra-terrestre ?",["George Lucas","Steven Spielberg","Ridley Scott","Francis Ford Coppola"],1],
  ["Quel est le personnage principal de la série Dexter ?",["Dexter Morgan","Walter White","Tony Soprano","Don Draper"],0],
  ["Quelle est la première apparition de Spider-Man au cinéma ?",["2002","2004","2007","2012"],0],
  ["Qui joue le rôle de Black Panther ?",["Chadwick Boseman","Michael B. Jordan","Idris Elba","Lupita Nyong'o"],0],
  ["Quel film de Stanley Kubrick sort en 1968 ?",["2001: L'Odyssée de l'espace","Orange Mécanique","Shining","Full Metal Jacket"],0],
  ["Quelle série raconte l'histoire d'une famille dans le trafic de drogue ?",["Ozark","Narcos","Breaking Bad","Queen of the South"],0],
  ["Quel est le nom du vaisseau spatial dans Alien ?",["Nostromo","USS Enterprise","Millennium Falcon","Discovery"],0],
  ["Quel film de Pixar met en scène des émotions dans la tête d'une fillette ?",["Toy Story","Vice-Versa","Moi, moche et méchant","Les Nouveaux Héros"],1],
  ["Qui a réalisé Taxi Driver ?",["Francis Ford Coppola","Martin Scorsese","Brian De Palma","Sidney Lumet"],1],
  ["Quel est le nom du créateur de la série Les Simpsons ?",["Seth MacFarlane","Matt Groening","Trey Parker","Mike Judge"],1],
  ["Dans quel film Brad Pitt joue-t-il un personnage qui ne vieillit pas ?",["Fight Club","Inglourious Basterds","L'Étrange Histoire de Benjamin Button","Ocean's Eleven"],2],
  ["Quelle est la saga cinématographique la plus rentable ?",["Harry Potter","Le Seigneur des Anneaux","Star Wars","Marvel Cinematic Universe"],3],
  ["Qui joue le rôle de Hermione Granger ?",["Emma Watson","Keira Knightley","Natalie Portman","Bonnie Wright"],0],
  ["Quel film de Ridley Scott met en scène un gladiateur ?",["Gladiator","Robin des Bois","Blade Runner","Alien"],0],
  ["Dans quelle série trouve-t-on le personnage de Sheldon Cooper ?",["The Big Bang Theory","Friends","How I Met Your Mother","Scrubs"],0],
  ["Qui a réalisé Le Parrain (The Godfather) ?",["Martin Scorsese","Francis Ford Coppola","Brian De Palma","Sergio Leone"],1],
  ["Quel est le film d'animation le plus rentable de l'histoire ?",["Le Roi Lion","Frozen","Le Monde de Nemo","La Reine des Neiges 2"],3],
  ["Quel film de Tim Burton met en scène un personnage aux ciseaux pour mains ?",["Batman","Edward aux mains d'argent","Charlie et la Chocolaterie","Big Fish"],1],
  ["Qui a composé la musique de la saga Star Wars ?",["Hans Zimmer","John Williams","Howard Shore","Danny Elfman"],1],
  ["Quelle série met en scène un cheval ancienne star de sitcom ?",["South Park","Rick et Morty","BoJack Horseman","Family Guy"],2],
  ["Dans quel film Marlon Brando dit-il une offre qu'on ne peut pas refuser ?",["Apocalypse Now","Sur les quais","Le Parrain","Un tramway nommé Désir"],2],
  ["Quel est le premier film de la saga Fast and Furious ?",["Fast and Furious (2001)","2 Fast 2 Furious","Tokyo Drift","Fast and Furious 5"],0],
  ["Qui a réalisé Jurassic Park ?",["Steven Spielberg","George Lucas","James Cameron","Ridley Scott"],0],
  ["Quel personnage de Friends est monitrice de chants pour enfants ?",["Rachel","Monica","Phoebe","Chandler"],2],
  ["Quel film de Pixar raconte l'histoire d'un vieux monsieur qui s'envole ?",["Vice-Versa","Ratatouille","Là-haut","Soul"],2],
  ["Qui incarne Thor dans le MCU ?",["Chris Hemsworth","Chris Evans","Tom Hiddleston","Liam Hemsworth"],0],
  ["Dans quel film trouve-t-on le personnage de Gollum ?",["Le Seigneur des Anneaux","Harry Potter","Narnia","Le Hobbit"],0],
  ["Qui a réalisé le film Amélie Poulain ?",["Luc Besson","Jean-Pierre Jeunet","François Ozon","Claude Lelouch"],1],
  ["Quel est le nom du vaisseau de Han Solo ?",["X-Wing","Millennium Falcon","Star Destroyer","USS Enterprise"],1],
  ["Quelle série met en scène un serial killer qui ne tue que des meurtriers ?",["Hannibal","Dexter","Mindhunter","True Detective"],1],
  ["Quel film de Alfonso Cuarón raconte la survie dans l'espace ?",["Interstellar","Gravity","The Martian","Apollo 13"],1],
  ["Qui joue le rôle du Joker dans Joker (2019) ?",["Jared Leto","Heath Ledger","Joaquin Phoenix","Jack Nicholson"],2],
  ["Quel film de Quentin Tarantino raconte l'histoire d'un esclave ?",["Inglourious Basterds","Django Unchained","Kill Bill","Les Huit Salopards"],1],
  ["Quelle série met en scène des adolescents confrontés au surnaturel dans les années 80 ?",["Riverdale","13 Reasons Why","Stranger Things","The Society"],2],
  ["Qui a réalisé le film Seven (Se7en) ?",["David Fincher","Christopher Nolan","Martin Scorsese","Steven Soderbergh"],0],
  ["Quelle est la planète d'origine de Superman ?",["Krypton","Gotham","Asgard","Tatooine"],0],
  ["Quel film a valu à Will Smith son premier Oscar ?",["Ali","King Richard","En attendant l'éternité","La Poursuite du bonheur"],1],
  ["Dans quel film Julia Roberts joue-t-elle une call-girl ?",["Pretty Woman","Notting Hill","Erin Brockovich","My Best Friend's Wedding"],0],
  ["Quelle est la première œuvre de l'Univers Cinématographique Marvel ?",["Iron Man","The Incredible Hulk","Captain America","Thor"],0],
  ["Quel film de Christopher Nolan raconte le vol d'inversions temporelles ?",["Inception","Interstellar","Tenet","Dunkirk"],2],
  ["Combien de films composent la saga Le Seigneur des Anneaux (version cinéma) ?",["2","3","4","6"],1],
  ["Quel acteur incarne Dracula dans le film de Coppola (1992) ?",["Bela Lugosi","Christopher Lee","Gary Oldman","Tom Cruise"],2],
  ["Dans quel film Tom Cruise court-il dans un couloir d'hôtel ?",["Mission: Impossible","Jerry Maguire","Risque Maximum","Collatéral"],1],
  ["Qui a réalisé le film Blade Runner ?",["Steven Spielberg","Ridley Scott","James Cameron","Denis Villeneuve"],1],
  ["Quel film de Luc Besson met en scène un nettoyeur professionnel ?",["Léon","Nikita","Le Cinquième Élément","Taxi"],0],
  ["Quelle est la série la plus longue de l'histoire de la télévision ?",["Les Simpson","Les Feux de l'amour","South Park","Grey's Anatomy"],1],
  ["Qui joue le rôle de Wolverine dans les films X-Men ?",["Chris Evans","Hugh Jackman","Ryan Reynolds","Tom Hardy"],1],
  ["Quel film de George Lucas est sorti en 1977 ?",["American Graffiti","THX 1138","Star Wars","Indiana Jones"],2],
  ["Quelle série HBO met en scène la guerre des gangs à Baltimore ?",["The Sopranos","The Wire","Boardwalk Empire","Peaky Blinders"],1],
  ["Dans quel film Robert De Niro joue-t-il un taxi driver solitaire ?",["Raging Bull","Les Affranchis","Taxi Driver","Casino"],2],
  ["Qui a réalisé le film La Liste de Schindler ?",["Steven Spielberg","Ridley Scott","Francis Ford Coppola","Roman Polanski"],0],
  ["Quelle actrice française remporte l'Oscar pour La Vie en rose ?",["Marion Cotillard","Juliette Binoche","Catherine Deneuve","Isabelle Huppert"],0],
  ["Quelle série de science-fiction met en scène un équipage de l'USS Enterprise ?",["Battlestar Galactica","Stargate","Star Trek","Babylon 5"],2],
  ["Dans quel film Matt Damon joue-t-il un agent amnésique ?",["Good Will Hunting","La Mémoire dans la peau","Interstellar","Les Infiltrés"],1],
  ["Qui a réalisé Psychose (1960) ?",["Alfred Hitchcock","Stanley Kubrick","Billy Wilder","Fritz Lang"],0],
  ["Quel est le nom de la ville de Batman ?",["Metropolis","Gotham City","Star City","Central City"],1],
  ["Qui incarne l'agent 007 dans Skyfall (2012) ?",["Pierce Brosnan","Daniel Craig","Sean Connery","Roger Moore"],1],
  ["Quel film de Brad Bird met en scène une famille de super-héros ?",["Les Indestructibles","Ratatouille","Le Géant de fer","Mission: Impossible 4"],0],
  ["Quelle série anime met en scène des ninjas adolescents ?",["Dragon Ball","Naruto","One Piece","Bleach"],1],
  ["Qui a réalisé le film Dune (2021) ?",["Denis Villeneuve","Christopher Nolan","Ridley Scott","Steven Spielberg"],0],
  ["Quel film de Pixar met en scène un poisson clown ?",["Le Monde de Nemo","Le Monde de Dory","Recherche Nemo","Trouver Nemo"],0],
  ["Quelle actrice a joué Katniss Everdeen ?",["Emma Stone","Jennifer Lawrence","Shailene Woodley","Kirsten Stewart"],1],
  ["Dans quel film de Spielberg un jeune garçon befriende un extraterrestre ?",["E.T.","Rencontres du troisième type","A.I.","War of the Worlds"],0],
  ["Qui a composé la musique du film Le Seigneur des Anneaux ?",["John Williams","Howard Shore","Hans Zimmer","Enya"],1],
  ["Quel film français de 2011 a remporté l'Oscar du meilleur film étranger ?",["Intouchables","Les Choristes","Amélie","Le Fabuleux Destin d'Amélie Poulain"],0],
  ["Dans quel film de Woody Allen se déroule l'action à Paris ?",["Minuit à Paris","Annie Hall","Manhattan","Vicky Christina Barcelona"],0],
  ["Quelle est la saga de films d'horreur la plus rentable ?",["Saw","Jeepers Creepers","It","Conjuring"],3],
  ["Qui a réalisé The Revenant (2015) ?",["Steven Spielberg","Alejandro González Iñárritu","Martin Scorsese","Terrence Malick"],1],
  ["Quelle série française met en scène Arsène Lupin ?",["Lupin","Marianne","Dix pour cent","Le Bureau des Légendes"],0],
  ["Dans quel film Tom Hanks survit-il sur une île déserte ?",["Forrest Gump","Cast Away","The Terminal","Sully"],1],
  ["Quelle est la nationalité du réalisateur Akira Kurosawa ?",["Coréenne","Japonaise","Chinoise","Thaïlandaise"],1],
  ["Qui incarne Black Widow dans le MCU ?",["Scarlett Johansson","Elizabeth Olsen","Karen Gillan","Zoe Saldana"],0],
  ["Quelle comédie française avec Jean Dujardin raconte le cinéma muet ?",["The Artist","Intouchables","OSS 117","Brice de Nice"],0],
  ["Dans quelle série japonaise trouve-t-on des colosses titanesques ?",["Naruto","One Piece","L'Attaque des Titans","Dragon Ball"],2],
  ["Qui a réalisé le film Shining ?",["David Lynch","Stanley Kubrick","Brian De Palma","John Carpenter"],1],
  ["Quel film de James Bond est sorti en 1962 ?",["Bons Baisers de Russie","Goldfinger","James Bond 007 contre Dr. No","Opération Tonnerre"],2],
  ["Quelle est la saga d'animation DreamWorks avec un ogre ?",["Kung Fu Panda","Comment dresser votre dragon","Shrek","Madagascar"],2],
  ["Qui a réalisé le film Le Labyrinthe de Pan ?",["Guillermo del Toro","Alejandro Amenábar","Pedro Almodóvar","Luis Buñuel"],0],
  ["Quel est le nom du super-vilain dans le premier Spider-Man (2002) ?",["Le Bouffon Vert","Le Dr Octopus","Venom","Sable"],0],
  ["Dans quel film de science-fiction Keanu Reeves vit-il dans une matrice ?",["Matrix","Johnny Mnemonic","Speed","John Wick"],0],
  ["Qui a remporté l'Oscar du meilleur réalisateur pour Parasite ?",["Bong Joon-ho","Quentin Tarantino","Martin Scorsese","Sam Mendes"],0],
  ["Quel est le premier film en couleur des studios Disney ?",["Blanche-Neige","Fantasia","Le Bossu de Notre-Dame","Pinocchio"],1],
  ["Quelle série britannique met en scène Sherlock Holmes moderne ?",["Luther","Broadchurch","Sherlock","Midsomer Murders"],2],
  ["Dans quel film de Pixar une vieille dame et un scout voyagent ?",["Là-haut","Ratatouille","Vice-Versa","Soul"],0],
  ["Qui joue le rôle de Captain America ?",["Robert Downey Jr.","Chris Evans","Chris Hemsworth","Jeremy Renner"],1],
  ["Quel film d'Akira Kurosawa a inspiré Les Sept Mercenaires ?",["Les Sept Samouraïs","Rashomon","Yojimbo","Ran"],0],
  ["Qui a réalisé les films de la trilogie Le Hobbit ?",["Peter Jackson","Guillermo del Toro","Steven Spielberg","James Cameron"],0],
  ["Quelle comédie romantique est la plus rentable de tous les temps ?",["Pretty Woman","Mamma Mia!","Titanic","My Big Fat Greek Wedding"],3],
  ["Qui incarne Thanos dans les films Avengers ?",["Josh Brolin","Tom Hardy","Mark Strong","Idris Elba"],0],
  ["Quel est le nom du personnage principal de Peaky Blinders ?",["Thomas Shelby","Alfie Solomons","Arthur Shelby","John Shelby"],0],
  ["Quelle actrice française a joué dans Inglourious Basterds ?",["Marion Cotillard","Mélanie Laurent","Léa Seydoux","Audrey Tautou"],1],
  ["Quel film de Luc Besson met en scène un agent et une extra-terrestre ?",["Léon","Le Cinquième Élément","Nikita","Arthur et les Minimoys"],1],
  ["Quelle série anime met en scène un pirate qui veut devenir le Roi des Pirates ?",["One Piece","Naruto","Dragon Ball","Bleach"],0],
  ["Qui a réalisé Alien (1979) ?",["James Cameron","Ridley Scott","David Fincher","Jean-Pierre Jeunet"],1],
  ["Quel film de Stanley Kubrick est sorti en 1971 ?",["2001: L'Odyssée de l'espace","Orange Mécanique","Shining","Full Metal Jacket"],1],
  ["Qui joue le rôle principal dans le film Drive (2011) ?",["Ryan Gosling","Tom Hardy","Oscar Isaac","Michael Fassbender"],0],
  ["Quelle est la saga avec les Hunger Games ?",["Divergente","Twilight","Hunger Games","Le Seigneur des Anneaux"],2],
  ["Quel réalisateur est célèbre pour ses plan-séquence ?",["Alfred Hitchcock","Orson Welles","Stanley Kubrick","Brian De Palma"],1],
  ["Dans quel film de Pixar un rat devient chef cuisinier ?",["Le Monde de Nemo","Ratatouille","Là-haut","Cars"],1],
  ["Qui a réalisé le film La Haine (1995) ?",["Luc Besson","Mathieu Kassovitz","Jean-Pierre Jeunet","Cédric Klapisch"],1],
  ["Quelle série Netflix raconte l'histoire d'une reine ?",["The Crown","Reign","Victoria","The Great"],0],
  ["Quel film de Pixar sort en 2020 et parle de la musique ?",["Soul","Coco","Vice-Versa","Là-haut"],0],
  ["Qui a incarné Dracula dans la série NBC Hannibal ?",["Anthony Hopkins","Mads Mikkelsen","Gary Oldman","Bela Lugosi"],1],
  ["Quel est le nom du chat de Shrek ?",["Compagnon","Puss","Chat Botté","Noune"],0],
  ["Dans quel film de Christopher Nolan le temps est inversé ?",["Inception","Tenet","Interstellar","Memento"],1],
  ["Qui est la réalisatrice de Wonder Woman ?",["Patty Jenkins","Catherine Hardwicke","Nia DaCosta","Greta Gerwig"],0],
  ["Quel film de Pixar met en scène une famille colombienne magique ?",["Coco","Encanto","Vice-Versa","Soul"],1],
  ["Quelle série française raconte la vie de professeurs ?",["Lupin","Kaamelott","Marianne","Plan Cœur"],3],
  ["Qui a joué dans les films Twilight ?",["Robert Pattinson","Daniel Radcliffe","Andrew Garfield","Tobey Maguire"],0],
  ["Quel est le film d'horreur le plus rentable ?",["It","Conjuring","Saw","Exorciste"],0],
  ["Qui a réalisé le film Joker (2019) ?",["Christopher Nolan","Todd Phillips","David Fincher","Martin Scorsese"],1],
  ["Quelle actrice a remporté l'Oscar pour Blue Jasmine ?",["Meryl Streep","Cate Blanchett","Sandra Bullock","Natalie Portman"],1],
  ["Quel est le film le plus oscarisé de l'histoire ?",["Titanic","Ben-Hur","La Liste de Schindler","West Side Story"],0],
  ["Dans quelle série trouve-t-on le personnage de Rick Grimes ?",["The Walking Dead","Fear the Walking Dead","The Last of Us","Left for Dead"],0],
  ["Qui a réalisé le film Gladiator ?",["Ridley Scott","Steven Spielberg","Oliver Stone","Tony Scott"],0],
  ["Quelle série Netflix met en scène un cheat game ?",["Squid Game","Alice in Borderland","Money Heist","Dark"],0],
  ["Quel film de Martin Scorsese raconte la vie d'un trader ?",["Les Affranchis","Casino","Le Loup de Wall Street","Shutter Island"],2],
  ["Qui a incarné Hermione dans la saga Harry Potter ?",["Emma Watson","Bonnie Wright","Evanna Lynch","Katie Leung"],0],
  ["Quel film d'animation a pour héros un panda ?",["Kung Fu Panda","Madagascar","Rebel","Turbo"],0],
  ["Quelle est la série spin-off de Breaking Bad ?",["Better Call Saul","Ozark","Narcos","Fargo"],0],
  ["Dans quel film de Spielberg un garçon découvre des dinosaures ?",["Jurassic Park","Parc Jurassic","Monde Jurassique","Le Monde Perdu"],0],
  ["Qui a réalisé Le fabuleux destin d'Amélie Poulain ?",["Luc Besson","Jean-Pierre Jeunet","François Ozon","Claude Lelouch"],1],
  ["Quelle est la série Disney la plus regardée sur Disney+ ?",["The Mandalorian","Loki","WandaVision","The Falcon and the Winter Soldier"],0],
  ["Quel film de James Cameron a dépassé Avatar au box-office ?",["Titanic","Avatar 2","Terminator 2","Aliens"],1],
  ["Qui a joué dans le film La Vérité si je mens ?",["Gérard Depardieu","José Garcia","Gad Elmaleh","Jean Dujardin"],0],
  ["Quelle est la dernière série de David Lynch ?",["Twin Peaks","Les Mystères de Twin Peaks","Mulholland Drive","Blue Velvet"],0],
  ["Quel acteur a joué dans les 3 films Batman de Nolan ?",["Christian Bale","Michael Keaton","George Clooney","Ben Affleck"],0],
  ["Quel film de Pixar met en scène un robot nettoyeur ?",["WALL-E","Cars","Ratatouille","Le Monde de Nemo"],0],
  ["Quelle série française met en scène un gangster à Marseille ?",["Mafia","Mafiosa","Baron Noir","Spiral"],1],
  ["Qui a réalisé le film Social Network ?",["David Fincher","Aaron Sorkin","Christopher Nolan","Ben Affleck"],0],
  ["Quel film de comédie française est le plus vu en France ?",["Bienvenue chez les Ch'tis","Intouchables","Le Dîner de Cons","Astérix et Obélix"],0],
  ["Dans quel film de Pixar des monstres font peur aux enfants ?",["Monstres et Compagnie","Vice-Versa","Toy Story","Là-haut"],0],
  ["Qui incarne la Panthère Noire dans le MCU ?",["Chadwick Boseman","Michael B. Jordan","Idris Elba","Letitia Wright"],0],
  ["Quel film a remporté l'Oscar du meilleur film en 2020 ?",["1917","Parasite","Joker","Once Upon a Time in Hollywood"],1],
  ["Quelle série de HBO est considérée comme la meilleure de tous les temps ?",["Game of Thrones","The Sopranos","The Wire","Band of Brothers"],1],
  ["Qui a réalisé les films de la trilogie Bourne ?",["Paul Greengrass","Doug Liman","Christopher Nolan","Tony Scott"],1],
  ["Quel film français raconte l'histoire d'un agriculteur ?",["Intouchables","Au revoir là-haut","La Guerre des boutons","Entre les murs"],1],
  ["Quelle actrice a joué dans Black Widow ?",["Scarlett Johansson","Florence Pugh","Elizabeth Olsen","Rachel Weisz"],0],
  ["Dans quel film de Cameron Diaz et Jim Carrey se rencontrent-ils ?",["The Mask","Bruce tout-puissant","Ace Ventura","Dumb and Dumber"],0],
];

export const csCash = [
  ["Comment s'appelle le réalisateur du film Titanic ?",["james cameron","cameron"]],
  ["Quel est le nom du personnage principal de la saga Harry Potter ?",["harry potter","potter","harry"]],
  ["Comment s'appelle le vaisseau spatial dans Star Wars piloté par Han Solo ?",["millennium falcon","faucon millenium","faucon millennnium"]],
  ["Quel acteur incarne Wolverine ?",["hugh jackman","jackman"]],
  ["Comment s'appelle le créateur de la série Breaking Bad ?",["vince gilligan","gilligan"]],
  ["Quel est le nom du robot dans le film WALL-E ?",["wall-e","walle","wally"]],
  ["Qui a réalisé le film E.T. l'extra-terrestre ?",["steven spielberg","spielberg"]],
  ["Comment s'appelle la planète d'origine de Superman ?",["krypton"]],
  ["Quel est le nom du héros joué par Keanu Reeves dans Matrix ?",["neo"]],
  ["Comment s'appelle le méchant dans le film Le Roi Lion de Disney ?",["scar"]],
  ["Quel acteur a joué Forrest Gump ?",["tom hanks","hanks"]],
  ["Comment s'appelle le fil d'actualités du film The Social Network ?",["facebook"]],
  ["Quel est le nom du chat dans Shrek ?",["chat botte","puss","compagnon"]],
  ["Qui incarne Captain America dans le MCU ?",["chris evans","evans"]],
  ["Comment s'appelle la ville fictive où vit Batman ?",["gotham","gotham city"]],
  ["Quel est le nom de la sorcière dans Blanche-Neige ?",["reine mauvaise","méchante reine","grimhilde"]],
  ["Quel réalisateur a créé la saga Star Wars ?",["george lucas","lucas"]],
  ["Comment s'appelle le personnage principal de la série The Sopranos ?",["tony soprano","soprano","anthony soprano"]],
  ["Quel film a remporté l'Oscar du meilleur film en 1994 ?",["forrest gump","pulp fiction","la liste de schindler","schindler"]],
  ["Qui a joué le rôle de la Panthère Noire ?",["chadwick boseman","boseman"]],
  ["Comment s'appelle la planète des Ewoks dans Star Wars ?",["endor"]],
  ["Quel est le nom du personnage de Jim Carrey dans The Mask ?",["stanley ipkiss","ipkiss"]],
  ["Qui a réalisé la trilogie Le Seigneur des Anneaux ?",["peter jackson","jackson"]],
  ["Comment s'appelle le chien de Tintin ?",["milou"]],
  ["Quel est le nom du plus célèbre film d'Alfred Hitchcock ?",["psychose","vertigo","les oiseaux","la mort aux trousses"]],
  ["Qui a incarné le Joker dans le film de 2019 ?",["joaquin phoenix","phoenix"]],
  ["Comment s'appelle la série Netflix sur un jeu mortel sud-coréen ?",["squid game","squid"]],
  ["Quel est le nom du frère de Loki dans les films Marvel ?",["thor"]],
  ["Qui a réalisé le film Dune (2021) ?",["denis villeneuve","villeneuve"]],
  ["Comment s'appelle le héros de la saga Star Wars ?",["luke skywalker","skywalker","luke"]],
  ["Quel film français avec Omar Sy et François Cluzet ?",["intouchables"]],
  ["Comment s'appelle le personnage de Gérard Depardieu dans Astérix ?",["obélix","obelix"]],
  ["Qui a composé la musique du film Le Parrain ?",["nino rota","rota"]],
  ["Quel est le nom du robot dans Star Wars ?",["r2-d2","r2d2","artoo","c-3po","c3po"]],
  ["Comment s'appelle le méchant de la saga Star Wars ?",["darth vader","vader","dark vador"]],
  ["Quel film de Pixar met en scène un poisson clown ?",["le monde de nemo","nemo","finding nemo"]],
  ["Qui a réalisé le film Fight Club ?",["david fincher","fincher"]],
  ["Comment s'appelle la ville où vit Spider-Man ?",["new york","manhattan"]],
  ["Quel est le nom du dragon de Shrek ?",["dragon"]],
  ["Qui a incarné Iron Man dans le MCU ?",["robert downey jr","robert downey junior","downey"]],
  ["Comment s'appelle le génie dans Aladdin ?",["genie"]],
  ["Quel est le nom du personnage principal de la série Dexter ?",["dexter morgan","dexter","morgan"]],
  ["Qui a créé la série South Park ?",["trey parker","matt stone","parker","stone"]],
  ["Comment s'appelle le film de Cameron avec des aliens bleus ?",["avatar"]],
  ["Quel est le nom du cheval de Gandalf ?",["ombreval","shadowfax"]],
  ["Qui a incarné le Dr Strange dans le MCU ?",["benedict cumberbatch","cumberbatch"]],
  ["Comment s'appelle le film de Christopher Nolan sur les rêves ?",["inception"]],
  ["Quel acteur a incarné Gatsby dans le film de 2013 ?",["leonardo dicaprio","dicaprio"]],
  ["Comment s'appelle la saga de films sur un jeune sorcier ?",["harry potter","potter"]],
  ["Qui a joué dans le film La Haine ?",["vincent cassel","cassel","hubert kounde","said taghmaoui"]],
  ["Quel est le nom du personnage de Julia Roberts dans Pretty Woman ?",["vivian ward","vivian"]],
  ["Comment s'appelle le vampire dans la saga Twilight ?",["edward cullen","edward","cullen"]],
  ["Qui a réalisé le film Alien ?",["ridley scott","scott"]],
];
