// Part 1: Culture Générale MCQ + Cash questions data
export const cgMCQ = [
  ["Quel est le plus grand pays du monde par superficie ?",["Chine","Canada","Russie","États-Unis"],2],
  ["Combien de continents y a-t-il sur Terre ?",["5","6","7","8"],2],
  ["Quelle est la monnaie du Japon ?",["Won","Yuan","Yen","Ringgit"],2],
  ["Combien d'os compte le corps humain adulte ?",["186","206","226","246"],1],
  ["Quel est le plus long fleuve de France ?",["Seine","Rhône","Loire","Garonne"],2],
  ["Quelle planète est surnommée la Planète Rouge ?",["Vénus","Jupiter","Mars","Saturne"],2],
  ["Qui a peint la Joconde ?",["Michel-Ange","Raphaël","Léonard de Vinci","Botticelli"],2],
  ["Quelle est la capitale de l'Australie ?",["Sydney","Melbourne","Canberra","Brisbane"],2],
  ["Quel est le plus grand océan du monde ?",["Atlantique","Indien","Arctique","Pacifique"],3],
  ["En quelle année la Révolution française a-t-elle commencé ?",["1776","1789","1792","1804"],1],
  ["Quel gaz les plantes absorbent-elles lors de la photosynthèse ?",["Oxygène","Azote","Dioxyde de carbone","Hydrogène"],2],
  ["Combien de couleurs y a-t-il dans un arc-en-ciel ?",["5","6","7","8"],2],
  ["Quel est l'animal terrestre le plus rapide ?",["Lion","Guépard","Gazelle","Cheval"],1],
  ["Quelle est la langue officielle du Brésil ?",["Espagnol","Portugais","Français","Anglais"],1],
  ["Combien y a-t-il de départements en France métropolitaine ?",["86","94","96","101"],2],
  ["Quel est le symbole chimique de l'or ?",["Or","Ag","Au","Fe"],2],
  ["Qui a écrit Les Misérables ?",["Émile Zola","Victor Hugo","Gustave Flaubert","Alexandre Dumas"],1],
  ["Quelle est la plus petite planète du système solaire ?",["Mars","Vénus","Mercure","Pluton"],2],
  ["Quel pays a la forme d'une botte ?",["Grèce","Espagne","Italie","Portugal"],2],
  ["Combien de dents a un adulte humain ?",["28","30","32","34"],2],
  ["Quelle est la capitale de la Turquie ?",["Istanbul","Ankara","Izmir","Antalya"],1],
  ["Quel est le plus haut sommet du monde ?",["Mont Blanc","K2","Everest","Kilimandjaro"],2],
  ["Combien de côtés a un hexagone ?",["5","6","7","8"],1],
  ["Quel est le plus grand désert du monde ?",["Sahara","Gobi","Antarctique","Kalahari"],2],
  ["Quelle est la devise de la France ?",["Liberté, Égalité, Fraternité","Liberté, Justice, Paix","Liberté, Égalité, Solidarité","Liberté, Égalité, Démocratie"],0],
  ["Qui a découvert la pénicilline ?",["Louis Pasteur","Alexander Fleming","Marie Curie","Robert Koch"],1],
  ["Quel est le plus grand mammifère du monde ?",["Éléphant d'Afrique","Baleine bleue","Girafe","Rhinocéros"],1],
  ["Combien de lettres compte l'alphabet français ?",["24","25","26","27"],2],
  ["Quelle est la capitale du Canada ?",["Toronto","Vancouver","Montréal","Ottawa"],3],
  ["Quel organe du corps humain filtre le sang ?",["Cœur","Foie","Rein","Poumon"],2],
  ["Quel est le nom du plus grand télescope spatial ?",["Hubble","Spitzer","James Webb","Kepler"],2],
  ["Quelle est la vitesse de la lumière (approximativement) ?",["200 000 km/s","300 000 km/s","400 000 km/s","500 000 km/s"],1],
  ["Combien de planètes y a-t-il dans le système solaire ?",["6","7","8","9"],2],
  ["Quelle est la plus grande île du monde ?",["Madagascar","Bornéo","Groenland","Nouvelle-Guinée"],2],
  ["Qui a inventé le téléphone ?",["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Guglielmo Marconi"],2],
  ["Quelle est la capitale de l'Égypte ?",["Le Caire","Alexandrie","Louxor","Gizeh"],0],
  ["Combien de sens possède l'être humain ?",["4","5","6","7"],1],
  ["Quel pays est surnommé le pays du matin calme ?",["Japon","Corée du Sud","Vietnam","Thaïlande"],1],
  ["Quelle est la religion la plus pratiquée dans le monde ?",["Islam","Hindouisme","Christianisme","Bouddhisme"],2],
  ["Combien de côtés a un triangle ?",["2","3","4","5"],1],
  ["Quel est le plus grand pays d'Europe par superficie ?",["France","Espagne","Suède","Ukraine"],3],
  ["Quelle est la plus grande mer intérieure du monde ?",["Mer Noire","Mer Caspienne","Mer Morte","Lac Supérieur"],1],
  ["Combien de litres de sang contient approximativement le corps humain ?",["3 litres","4 litres","5 litres","6 litres"],2],
  ["Quel scientifique a formulé la théorie de la relativité ?",["Isaac Newton","Niels Bohr","Albert Einstein","Stephen Hawking"],2],
  ["Quelle est la capitale de la Norvège ?",["Stockholm","Oslo","Helsinki","Copenhague"],1],
  ["Quel est le plus petit pays du monde ?",["Monaco","Vatican","San Marin","Malte"],1],
  ["Quelle est la saison la plus chaude dans l'hémisphère nord ?",["Printemps","Été","Automne","Hiver"],1],
  ["Combien de chromosomes possède l'être humain ?",["23","44","46","48"],2],
  ["Quelle est la capitale de l'Argentine ?",["Santiago","Buenos Aires","Lima","Montevideo"],1],
  ["Quel est l'élément chimique le plus abondant dans l'univers ?",["Hélium","Oxygène","Carbone","Hydrogène"],3],
  ["Combien y a-t-il de pays en Afrique ?",["44","48","54","60"],2],
  ["Quelle est la capitale de l'Irlande ?",["Belfast","Dublin","Cork","Galway"],1],
  ["Combien de faces a un cube ?",["4","5","6","8"],2],
  ["Quel fleuve traverse Paris ?",["Seine","Loire","Rhône","Marne"],0],
  ["Quelle est la langue la plus parlée en nombre de locuteurs natifs ?",["Anglais","Espagnol","Mandarin","Hindi"],2],
  ["Combien pèse environ un litre d'eau ?",["500 grammes","750 grammes","1 kilogramme","1,5 kilogramme"],2],
  ["Quel est le plus long mur du monde ?",["Mur de Berlin","Mur des Lamentations","Grande Muraille de Chine","Hadrian's Wall"],2],
  ["Quelle est la capitale de la Pologne ?",["Krakovie","Gdańsk","Varsovie","Wrocław"],2],
  ["Combien de couleurs y a-t-il dans le drapeau français ?",["2","3","4","5"],1],
  ["Quel oiseau est le symbole de la paix ?",["Aigle","Colombe","Hirondelle","Cygne"],1],
  ["Quelle est la planète la plus proche du Soleil ?",["Vénus","Mercure","Mars","Terre"],1],
  ["Combien y a-t-il de pays membres de l'Union européenne ?",["25","27","28","30"],1],
  ["Quel est le plus grand organe du corps humain ?",["Foie","Poumon","Peau","Intestin"],2],
  ["Quelle est la capitale de l'Inde ?",["Mumbai","New Delhi","Kolkata","Chennai"],1],
  ["Combien de temps met la lumière du Soleil pour atteindre la Terre ?",["4 minutes","8 minutes","12 minutes","16 minutes"],1],
  ["Quelle est la formule chimique de l'eau ?",["H2O2","HO","H2O","OH2"],2],
  ["Combien de touches y a-t-il sur un piano standard ?",["76","82","88","92"],2],
  ["Quelle est la capitale de la Suède ?",["Oslo","Stockholm","Copenhague","Helsinki"],1],
  ["Combien de secondes y a-t-il dans une minute ?",["30","45","60","90"],2],
  ["Quel est le plus long fleuve du monde ?",["Amazone","Nil","Mississippi","Yangtsé"],1],
  ["Quelle est la capitale de la Grèce ?",["Sparte","Athènes","Thessalonique","Patras"],1],
  ["Combien de mois y a-t-il dans une année ?",["10","11","12","13"],2],
  ["Quel est le plus petit os du corps humain ?",["Marteau","Étrier","Enclume","Rocher"],1],
  ["Quelle est la capitale du Pérou ?",["La Paz","Lima","Bogota","Quito"],1],
  ["Combien de jours y a-t-il dans une année bissextile ?",["364","365","366","367"],2],
  ["Quel est le point le plus profond des océans ?",["Fosse des Mariannes","Fosse des Tonga","Fosse du Japon","Fosse des Philippines"],0],
  ["Quelle est la capitale de l'Afrique du Sud (siège administratif) ?",["Le Cap","Johannesburg","Pretoria","Durban"],2],
  ["Combien d'heures y a-t-il dans une journée ?",["12","20","24","36"],2],
  ["Quel est le plus gros fruit du monde ?",["Pastèque","Melon","Potiron","Jacquier"],3],
  ["Quelle est la capitale du Mexique ?",["Guadalajara","Monterrey","Mexico","Puebla"],2],
  ["Combien d'yeux a la plupart des araignées ?",["2","4","6","8"],3],
  ["Quel pays a pour capitale Nairobi ?",["Éthiopie","Kenya","Tanzanie","Ouganda"],1],
  ["Combien de vertèbres compose la colonne vertébrale humaine ?",["28","30","33","36"],2],
  ["Quelle est la capitale de la Corée du Sud ?",["Pyeongyang","Séoul","Busan","Incheon"],1],
  ["Combien de côtés a un octogone ?",["6","7","8","10"],2],
  ["Quelle est la capitale de la Thaïlande ?",["Bangkok","Chiang Mai","Pattaya","Phuket"],0],
  ["Combien de continents l'équateur traverse-t-il ?",["1","2","3","4"],2],
  ["Quel est le seul mammifère capable de voler ?",["Écureuil volant","Phalanger","Chauve-souris","Lémur volant"],2],
  ["Quelle est la capitale de la Suisse ?",["Zurich","Genève","Berne","Bâle"],2],
  ["Combien de pièces y a-t-il dans un jeu d'échecs ?",["28","30","32","34"],2],
  ["Quel est le préfixe kilo en chiffres ?",["100","1 000","10 000","100 000"],1],
  ["Quelle est la capitale de la Colombie ?",["Bogota","Lima","Caracas","Quito"],0],
  ["Combien de pièces y a-t-il dans un jeu de dominos classique ?",["24","28","32","36"],1],
  ["Quel est le plus haut volcan actif d'Europe ?",["Etna","Vésuve","Stromboli","Vulcano"],0],
  ["Quelle est la capitale de la Tchéquie ?",["Bratislava","Prague","Budapest","Vienne"],1],
  ["Combien de pattes a un insecte ?",["4","6","8","10"],1],
  ["Quel animal peut dormir jusqu'à 22 heures par jour ?",["Chat","Koala","Paresseux","Sloth"],1],
  ["Quelle est la capitale de la Croatie ?",["Zagreb","Split","Dubrovnik","Rijeka"],0],
  ["Combien de cordes a une guitare classique ?",["4","5","6","8"],2],
  ["Quel est le plus grand lac du monde ?",["Lac Supérieur","Lac Victoria","Lac Baïkal","Mer Caspienne"],3],
  ["Quelle est la capitale du Vietnam ?",["Hanoï","Hô Chi Minh-Ville","Da Nang","Hué"],0],
  ["Combien de joueurs composent une équipe de volley-ball ?",["4","5","6","7"],2],
  ["Quel est le monument le plus visité de France ?",["Tour Eiffel","Mont Saint-Michel","Château de Versailles","Musée du Louvre"],0],
  ["Quelle est la capitale de l'Autriche ?",["Munich","Vienne","Zurich","Salzbourg"],1],
  ["Quel pays a la plus forte densité de population ?",["Singapour","Monaco","Vatican","Malte"],1],
  ["Quelle est la capitale du Nigeria ?",["Lagos","Abuja","Kano","Ibadan"],1],
  ["Combien de branches a une étoile à 5 branches ?",["5","10","15","20"],1],
  ["Quel est le plus grand parc national de France ?",["Vanoise","Écrins","Mercantour","Parc amazonien de Guyane"],3],
  ["Quelle est la capitale du Portugal ?",["Porto","Lisbonne","Faro","Coimbra"],1],
  ["Quel est le métal le plus léger ?",["Aluminium","Titane","Lithium","Magnésium"],2],
  ["Quelle est la capitale de la Roumanie ?",["Budapest","Bucarest","Sofia","Belgrade"],1],
  ["Quel est le plus ancien monument de Paris ?",["Notre-Dame","Panthéon","Arènes de Lutèce","Sainte-Chapelle"],2],
  ["Quelle est la capitale de la Finlande ?",["Stockholm","Oslo","Helsinki","Tallinn"],2],
  ["Combien de rayures a un zèbre en moyenne ?",["50","80","100","130"],2],
  ["Quelle est la capitale de la Serbie ?",["Sarajevo","Zagreb","Belgrade","Skopje"],2],
  ["Combien de cartes y a-t-il dans un jeu de 52 cartes ?",["48","50","52","54"],2],
  ["Quel pays est le plus grand exportateur de café ?",["Brésil","Colombie","Vietnam","Éthiopie"],0],
  ["Quelle est la capitale de la Tunisie ?",["Sfax","Sousse","Tunis","Kairouan"],2],
  ["Combien de phases a la Lune ?",["2","4","6","8"],1],
  ["Quelle est la capitale du Cambodge ?",["Phnom Penh","Luang Prabang","Hanoï","Bangkok"],0],
  ["Combien de trous y a-t-il sur un terrain de golf standard ?",["9","12","18","27"],2],
  ["Quelle est la capitale de la Nouvelle-Zélande ?",["Auckland","Wellington","Christchurch","Hamilton"],1],
  ["Combien d'années dure un mandat présidentiel en France ?",["4 ans","5 ans","6 ans","7 ans"],1],
  ["Quelle est la capitale de la Lituanie ?",["Riga","Tallinn","Vilnius","Kaunas"],2],
  ["Quel pays est celui qui compte le plus d'îles ?",["Indonésie","Philippines","Suède","Canada"],2],
  ["Quelle est la capitale du Bangladesh ?",["Dhaka","Chittagong","Calcutta","Yangon"],0],
  ["Combien y a-t-il de signes du zodiaque ?",["10","12","14","16"],1],
  ["Quel est le nombre d'or (approximativement) ?",["1,414","1,618","2,236","3,141"],1],
  ["Combien de pièces distinctes l'euro a-t-il ?",["6","7","8","10"],2],
  ["Quel scientifique a découvert la radioactivité ?",["Pierre Curie","Marie Curie","Henri Becquerel","Niels Bohr"],1],
  ["Quelle est la capitale de l'Irak ?",["Bagdad","Bassora","Erbil","Mossoul"],0],
  ["Combien d'os composent le crâne humain ?",["22","24","26","28"],0],
  ["Quelle est la capitale du Danemark ?",["Copenhague","Malmö","Oslo","Aarhus"],0],
  ["Combien de trompes a un éléphant ?",["1","2","3","0"],0],
  ["Quel est le symbole chimique du fer ?",["Ir","Fe","Fr","Fi"],1],
  ["Quelle est la capitale de la Mongolie ?",["Oulan-Bator","Astana","Bichkek","Douchanbé"],0],
  ["Quelle est la capitale du Congo-Brazzaville ?",["Kinshasa","Brazzaville","Pointe-Noire","Dolisie"],1],
  ["Quel est le nom du premier satellite artificiel ?",["Explorer 1","Sputnik 1","Vostok 1","Apollo 11"],1],
  ["Quelle est la capitale du Népal ?",["Katmandou","Pokhara","Lhassa","Dharamsala"],0],
  ["Quel est le plus profond lac du monde ?",["Lac Tanganyika","Lac Baïkal","Lac Supérieur","Lac Victoria"],1],
  ["Quelle est la capitale de la Bulgarie ?",["Sofia","Bucarest","Belgrade","Thessalonique"],0],
  ["Quel pays possède la plus grande réserve d'eau douce ?",["Canada","Russie","Brésil","États-Unis"],0],
  ["Quelle est la capitale de l'Uruguay ?",["Buenos Aires","Montevideo","Asunción","Santiago"],1],
  ["Quelle est la capitale du Ghana ?",["Accra","Kumasi","Lagos","Abidjan"],0],
  ["Quel est le plus grand continent du monde ?",["Afrique","Asie","Amérique","Europe"],1],
  ["Quelle est la capitale de la Slovénie ?",["Ljubljana","Zagreb","Vienne","Budapest"],0],
  ["Combien y a-t-il de pays en Amérique du Sud ?",["10","12","14","16"],1],
  ["Quelle est la vitesse du son dans l'air (approximativement) ?",["300 km/h","340 km/h","380 km/h","420 km/h"],1],
  ["Quel est le plus long tunnel ferroviaire du monde ?",["Tunnel sous la Manche","Tunnel du Gothard","Tunnel de Seikan","Tunnel de base du Brenner"],1],
  ["Quelle est la capitale de l'Ouzbékistan ?",["Tachkent","Samarcande","Boukhara","Douchanbé"],0],
];

export const cgCash = [
  ["Quel est le nom du président de la République française actuel ?",["emmanuel macron","macron"]],
  ["Combien de côtés possède un dodécagone ?",["douze","12"]],
  ["Quelle est la capitale de l'Allemagne ?",["berlin"]],
  ["Comment s'appelle le plus grand mammifère terrestre ?",["elephant d'afrique","elephant"]],
  ["Quel est le résultat de 7 fois 8 ?",["56","cinquante-six"]],
  ["Quelle est la monnaie du Royaume-Uni ?",["livre sterling","livre","pound"]],
  ["Quel est le plus haut bâtiment du monde ?",["burj khalifa"]],
  ["Combien de jours compte le mois de février en année non bissextile ?",["28","vingt-huit"]],
  ["Quel animal est surnommé le roi des animaux ?",["lion"]],
  ["Comment s'appelle la cathédrale la plus célèbre de Paris ?",["notre-dame","notre dame","cathedrale notre-dame"]],
  ["Quelle est la plus grande montagne de France ?",["mont blanc"]],
  ["Combien de minutes y a-t-il dans une heure ?",["60","soixante"]],
  ["Comment s'appelle le théâtre le plus célèbre de Londres ?",["shakespeare's globe","globe theatre","globe"]],
  ["Combien font racine carrée de 144 ?",["12","douze"]],
  ["Quel est le nom du plus grand désert chaud du monde ?",["sahara"]],
  ["Quelle est la capitale de l'Espagne ?",["madrid"]],
  ["Quel astre tourne autour de la Terre ?",["lune"]],
  ["Combien y a-t-il de semaines dans une année ?",["52","cinquante-deux"]],
  ["Quel est le symbole chimique du sodium ?",["na"]],
  ["Quelle est la plus grande ville de France par population ?",["paris"]],
  ["Combien d'anneaux olympiques y a-t-il ?",["5","cinq"]],
  ["Quel pays est surnommé le pays du soleil levant ?",["japon"]],
  ["Quelle est la matière dont sont composés les diamants ?",["carbone"]],
  ["Combien d'étoiles y a-t-il sur le drapeau de l'Union européenne ?",["12","douze"]],
  ["Quel est le nom du plus long fleuve d'Europe ?",["volga"]],
  ["Quelle est la température d'ébullition de l'eau en degrés Celsius ?",["100","cent"]],
  ["Combien de rayures comporte le drapeau américain ?",["13","treize"]],
  ["Quelle est la fleur symbole du Japon ?",["sakura","cerisier","fleur de cerisier"]],
  ["Quelle est la monnaie de la Chine ?",["yuan","renminbi","rmb"]],
  ["Combien d'os composent la face humaine ?",["14","quatorze"]],
  ["Quelle est la spécialité gastronomique de la ville de Marseille ?",["bouillabaisse"]],
  ["Combien de côtés possède un losange ?",["4","quatre"]],
  ["Quel est le nom du courant océanique qui réchauffe l'Europe ?",["gulf stream"]],
  ["Quelle est la plus petite planète du système solaire ?",["mercure"]],
  ["Quel est le nom du créateur de Facebook ?",["mark zuckerberg","zuckerberg"]],
  ["Quelle est la capitale du Chili ?",["santiago"]],
  ["Combien de points vaut la lettre A au Scrabble français ?",["1","un"]],
  ["Quel est le nom du plus grand pont suspendu de France ?",["viaduc de millau","millau"]],
  ["Quelle est la matière qui constitue la majorité du Soleil ?",["hydrogene"]],
  ["Combien de sens possède l'être humain ?",["5","cinq"]],
  ["Comment s'appelle le plus grand vaisseau spatial de l'histoire ?",["saturn v","saturn five"]],
  ["Quelle est la capitale de la Belgique ?",["bruxelles"]],
  ["Combien de côtés a un pentagone ?",["5","cinq"]],
  ["Quel est le nom du satellite naturel de la Terre ?",["lune"]],
  ["Quelle est la capitale de la Libye ?",["tripoli"]],
  ["Combien de lettres compte le mot le plus long en français ?",["25","vingt-cinq"]],
  ["Quel est le nom du musée d'art contemporain à New York ?",["moma","museum of modern art"]],
  ["Combien de parties compose un match de tennis ?",["2","3","cinq","5","trois"]],
  ["Quelle est la capitale de la Jamaïque ?",["kingston"]],
  ["Quel est le plus petit océan du monde ?",["arctique","ocean arctique"]],
  ["Combien de neurones le cerveau humain contient-il en milliards ?",["86","quatre-vingt-six","80","80-100"]],
  ["Quelle est la capitale de la Syrie ?",["damas"]],
  ["Combien de degrés y a-t-il dans un angle droit ?",["90","quatre-vingt-dix"]],
  ["Quel est le nom du créateur de Wikipedia ?",["jimmy wales","wales","larry sanger","sanger"]],
];
